" Name:         Rosé Pine Dawn
" Description:  All natural pine, faux fur and a bit of soho vibes for the classy minimalist
" Author:       Prateek Tade <prateek.tade@gmail.com>
" Maintainer:   Prateek Tade <prateek.tade@gmail.com>
" Website:      https://github.com/rose-pine/vim
" License:      Vim License (see `:help license`)
" Last Updated: Sun Jan 15 20:43:16 2023

" Generated by Colortemplate v2.2.0

set background=light

hi clear
let g:colors_name = 'rosepine_dawn'

let s:t_Co = exists('&t_Co') && !has('gui_running') ? (&t_Co ?? 0) : -1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link CurSearch IncSearch
hi! link diffAdded DiffAdd
hi! link diffChanged DiffChange
hi! link diffRemoved DiffDelete
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link WildMenu IncSearch
hi! link markdownH1Delimiter markdownH1
hi! link markdownH2Delimiter markdownH2
hi! link markdownH3Delimiter markdownH3
hi! link markdownH4Delimiter markdownH4
hi! link markdownH5Delimiter markdownH5
hi! link markdownH6Delimiter markdownH6
hi! link markdownURL markdownLinkText
hi! link mkdLink mkdInlineURL
hi! link mkdLinkDef mkdInlineURL
hi! link mkdURL mkdInlineURL

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#f2e9e1', '#b4637a', '#286983', '#ea9d34', '#56949f', '#907aa9', '#d7827e', '#575279', '#797593', '#b4637a', '#286983', '#ea9d34', '#56949f', '#907aa9', '#d7827e', '#575279']
endif
if get(g:,'disable_bg',0)
  hi Normal guifg=#575279 guibg=NONE gui=NONE cterm=NONE
  hi NormalNC guifg=#575279 guibg=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#575279 guibg=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#9893a5 guibg=NONE gui=NONE cterm=NONE
else
  hi Normal guifg=#575279 guibg=#faf4ed gui=NONE cterm=NONE
  hi NormalNC guifg=#575279 guibg=#faf4ed gui=NONE cterm=NONE
  hi SignColumn guifg=#575279 guibg=#faf4ed gui=NONE cterm=NONE
  hi StatusLineNC guifg=#9893a5 guibg=#faf4ed gui=NONE cterm=NONE
endif
if get(g:,'disable_float_bg',0)
  hi DarkenedPanel guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DarkenedStatusline guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Folded guifg=#575279 guibg=NONE gui=NONE cterm=NONE
  hi NormalFloat guifg=#575279 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#797593 guibg=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#797593 guibg=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#797593 guibg=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
else
  hi DarkenedPanel guifg=NONE guibg=#fffaf3 gui=NONE cterm=NONE
  hi DarkenedStatusline guifg=NONE guibg=#fffaf3 gui=NONE cterm=NONE
  hi Folded guifg=#575279 guibg=#fffaf3 gui=NONE cterm=NONE
  hi NormalFloat guifg=#575279 guibg=#fffaf3 gui=NONE cterm=NONE
  hi Pmenu guifg=#797593 guibg=#fffaf3 gui=NONE cterm=NONE
  hi StatusLine guifg=#797593 guibg=#fffaf3 gui=NONE cterm=NONE
  hi TabLine guifg=#797593 guibg=#fffaf3 gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#fffaf3 gui=NONE cterm=NONE
endif
if !s:italics 
  hi Comment guifg=#9893a5 guibg=NONE gui=NONE cterm=NONE
else
  hi Comment guifg=#9893a5 guibg=NONE gui=italic cterm=italic
  if !s:italics
    hi Comment gui=NONE cterm=NONE
  endif
endif
hi ColorColumn guifg=NONE guibg=#f2e9e1 gui=NONE cterm=NONE
hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi CursorColumn guifg=NONE guibg=#f4ede8 gui=NONE cterm=NONE
hi CursorLine guifg=NONE guibg=#f4ede8 gui=NONE cterm=NONE
hi CursorLineNr guifg=#575279 guibg=NONE gui=NONE cterm=NONE
hi DiffAdd guifg=NONE guibg=#d9e1dd gui=NONE cterm=NONE
hi DiffChange guifg=NONE guibg=#f2e9e1 gui=NONE cterm=NONE
hi DiffDelete guifg=NONE guibg=#ecd7d6 gui=NONE cterm=NONE
hi DiffText guifg=NONE guibg=#f3ddd7 gui=NONE cterm=NONE
hi Directory guifg=#56949f guibg=NONE gui=NONE cterm=NONE
hi ErrorMsg guifg=#b4637a guibg=NONE gui=bold cterm=bold
hi FloatBorder guifg=#dfdad9 guibg=NONE gui=NONE cterm=NONE
hi FloatTitle guifg=#9893a5 guibg=NONE gui=NONE cterm=NONE
hi FoldColumn guifg=#9893a5 guibg=NONE gui=NONE cterm=NONE
hi IncSearch guifg=#faf4ed guibg=#d7827e gui=NONE cterm=NONE
hi LineNr guifg=#9893a5 guibg=NONE gui=NONE cterm=NONE
hi MatchParen guifg=#575279 guibg=#dfdad9 gui=NONE cterm=NONE
hi ModeMsg guifg=#797593 guibg=NONE gui=NONE cterm=NONE
hi MoreMsg guifg=#907aa9 guibg=NONE gui=NONE cterm=NONE
hi NonText guifg=#9893a5 guibg=NONE gui=NONE cterm=NONE
hi PmenuSbar guifg=NONE guibg=#f4ede8 gui=NONE cterm=NONE
hi PmenuSel guifg=#575279 guibg=#f2e9e1 gui=NONE cterm=NONE
hi PmenuThumb guifg=NONE guibg=#dfdad9 gui=NONE cterm=NONE
hi Question guifg=#ea9d34 guibg=NONE gui=NONE cterm=NONE
hi Search guifg=NONE guibg=#dfdad9 gui=NONE cterm=NONE
hi SpecialKey guifg=#56949f guibg=NONE gui=NONE cterm=NONE
hi SpellBad guifg=NONE guibg=NONE guisp=#797593 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellCap guifg=NONE guibg=NONE guisp=#797593 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellLocal guifg=NONE guibg=NONE guisp=#797593 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellRare guifg=NONE guibg=NONE guisp=#797593 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi TabLineSel guifg=#575279 guibg=#f2e9e1 gui=NONE cterm=NONE
hi Title guifg=#575279 guibg=NONE gui=NONE cterm=NONE
hi VertSplit guifg=#dfdad9 guibg=NONE gui=NONE cterm=NONE
hi Visual guifg=NONE guibg=#dfdad9 gui=NONE cterm=NONE
hi WarningMsg guifg=#ea9d34 guibg=NONE gui=NONE cterm=NONE
hi Boolean guifg=#d7827e guibg=NONE gui=NONE cterm=NONE
hi Character guifg=#ea9d34 guibg=NONE gui=NONE cterm=NONE
hi Conditional guifg=#286983 guibg=NONE gui=NONE cterm=NONE
hi Constant guifg=#ea9d34 guibg=NONE gui=NONE cterm=NONE
hi Debug guifg=#d7827e guibg=NONE gui=NONE cterm=NONE
hi Define guifg=#907aa9 guibg=NONE gui=NONE cterm=NONE
hi Delimiter guifg=#797593 guibg=NONE gui=NONE cterm=NONE
hi Error guifg=#b4637a guibg=NONE gui=NONE cterm=NONE
hi Exception guifg=#286983 guibg=NONE gui=NONE cterm=NONE
hi Float guifg=#ea9d34 guibg=NONE gui=NONE cterm=NONE
hi Function guifg=#d7827e guibg=NONE gui=NONE cterm=NONE
hi Identifier guifg=#d7827e guibg=NONE gui=NONE cterm=NONE
hi Include guifg=#907aa9 guibg=NONE gui=NONE cterm=NONE
hi Keyword guifg=#286983 guibg=NONE gui=NONE cterm=NONE
hi Label guifg=#56949f guibg=NONE gui=NONE cterm=NONE
hi Macro guifg=#907aa9 guibg=NONE gui=NONE cterm=NONE
hi Number guifg=#ea9d34 guibg=NONE gui=NONE cterm=NONE
hi Operator guifg=#797593 guibg=NONE gui=NONE cterm=NONE
hi PreCondit guifg=#907aa9 guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#907aa9 guibg=NONE gui=NONE cterm=NONE
hi Repeat guifg=#286983 guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#d7827e guibg=NONE gui=NONE cterm=NONE
hi SpecialChar guifg=#d7827e guibg=NONE gui=NONE cterm=NONE
hi SpecialComment guifg=#907aa9 guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#286983 guibg=NONE gui=NONE cterm=NONE
hi StorageClass guifg=#56949f guibg=NONE gui=NONE cterm=NONE
hi String guifg=#ea9d34 guibg=NONE gui=NONE cterm=NONE
hi Structure guifg=#56949f guibg=NONE gui=NONE cterm=NONE
hi Tag guifg=#d7827e guibg=NONE gui=NONE cterm=NONE
hi Todo guifg=#907aa9 guibg=NONE gui=NONE cterm=NONE
hi Type guifg=#56949f guibg=NONE gui=NONE cterm=NONE
hi Typedef guifg=#56949f guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
hi htmlArg guifg=#907aa9 guibg=NONE gui=NONE cterm=NONE
hi htmlBold guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
hi htmlEndTag guifg=#797593 guibg=NONE gui=NONE cterm=NONE
hi htmlH1 guifg=#907aa9 guibg=NONE gui=bold cterm=bold
hi htmlH2 guifg=#56949f guibg=NONE gui=bold cterm=bold
hi htmlH3 guifg=#d7827e guibg=NONE gui=bold cterm=bold
hi htmlH4 guifg=#ea9d34 guibg=NONE gui=bold cterm=bold
hi htmlH5 guifg=#286983 guibg=NONE gui=bold cterm=bold
if !s:italics 
  hi htmlItalic guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
else
  hi htmlItalic guifg=NONE guibg=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  if !s:italics
    hi htmlItalic gui=NONE cterm=NONE
  endif
endif
hi htmlLink guifg=#907aa9 guibg=NONE gui=NONE cterm=NONE
hi htmlTag guifg=#797593 guibg=NONE gui=NONE cterm=NONE
hi htmlTagN guifg=#575279 guibg=NONE gui=NONE cterm=NONE
hi htmlTagName guifg=#56949f guibg=NONE gui=NONE cterm=NONE
hi markdownDelimiter guifg=#797593 guibg=NONE gui=NONE cterm=NONE
hi markdownH1 guifg=#907aa9 guibg=NONE gui=bold cterm=bold
hi markdownH2 guifg=#56949f guibg=NONE gui=bold cterm=bold
hi markdownH3 guifg=#d7827e guibg=NONE gui=bold cterm=bold
hi markdownH4 guifg=#ea9d34 guibg=NONE gui=bold cterm=bold
hi markdownH5 guifg=#286983 guibg=NONE gui=bold cterm=bold
hi markdownH6 guifg=#56949f guibg=NONE gui=bold cterm=bold
hi markdownLinkText guifg=#907aa9 guibg=NONE gui=underline cterm=underline
if !s:italics 
  hi mkdCode guifg=#56949f guibg=NONE gui=NONE cterm=NONE
else
  hi mkdCode guifg=#56949f guibg=NONE gui=italic cterm=italic
  if !s:italics
    hi mkdCode gui=NONE cterm=NONE
  endif
endif
hi mkdCodeDelimiter guifg=#d7827e guibg=NONE gui=NONE cterm=NONE
hi mkdCodeEnd guifg=#56949f guibg=NONE gui=NONE cterm=NONE
hi mkdCodeStart guifg=#56949f guibg=NONE gui=NONE cterm=NONE
hi mkdFootnotes guifg=#56949f guibg=NONE gui=NONE cterm=NONE
hi mkdID guifg=#56949f guibg=NONE gui=underline cterm=underline
hi mkdInlineURL guifg=#907aa9 guibg=NONE gui=underline cterm=underline
hi mkdListItemLine guifg=#575279 guibg=NONE gui=NONE cterm=NONE
hi mkdRule guifg=#797593 guibg=NONE gui=NONE cterm=NONE
hi VimwikiHR guifg=#797593 guibg=NONE gui=NONE cterm=NONE
hi VimwikiHeader1 guifg=#907aa9 guibg=NONE gui=bold cterm=bold
hi VimwikiHeader2 guifg=#56949f guibg=NONE gui=bold cterm=bold
hi VimwikiHeader3 guifg=#d7827e guibg=NONE gui=bold cterm=bold
hi VimwikiHeader4 guifg=#ea9d34 guibg=NONE gui=bold cterm=bold
hi VimwikiHeader5 guifg=#286983 guibg=NONE gui=bold cterm=bold
hi VimwikiHeader6 guifg=#56949f guibg=NONE gui=bold cterm=bold
hi VimwikiHeaderChar guifg=#286983 guibg=NONE gui=NONE cterm=NONE
hi VimwikiLink guifg=#907aa9 guibg=NONE gui=underline cterm=underline
hi VimwikiList guifg=#907aa9 guibg=NONE gui=NONE cterm=NONE
hi VimwikiNoExistsLink guifg=#b4637a guibg=NONE gui=NONE cterm=NONE

if s:t_Co >= 256
  if get(g:,'disable_bg',0)
    hi Normal ctermfg=60 ctermbg=NONE cterm=NONE
    hi NormalNC ctermfg=60 ctermbg=NONE cterm=NONE
    hi SignColumn ctermfg=60 ctermbg=NONE cterm=NONE
    hi StatusLineNC ctermfg=103 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=60 ctermbg=255 cterm=NONE
    hi NormalNC ctermfg=60 ctermbg=255 cterm=NONE
    hi SignColumn ctermfg=60 ctermbg=255 cterm=NONE
    hi StatusLineNC ctermfg=103 ctermbg=255 cterm=NONE
  endif
  if get(g:,'disable_float_bg',0)
    hi DarkenedPanel ctermfg=NONE ctermbg=NONE cterm=NONE
    hi DarkenedStatusline ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Folded ctermfg=60 ctermbg=NONE cterm=NONE
    hi NormalFloat ctermfg=60 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=103 ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=103 ctermbg=NONE cterm=NONE
    hi TabLine ctermfg=103 ctermbg=NONE cterm=NONE
    hi TabLineFill ctermfg=NONE ctermbg=NONE cterm=NONE
  else
    hi DarkenedPanel ctermfg=NONE ctermbg=231 cterm=NONE
    hi DarkenedStatusline ctermfg=NONE ctermbg=231 cterm=NONE
    hi Folded ctermfg=60 ctermbg=231 cterm=NONE
    hi NormalFloat ctermfg=60 ctermbg=231 cterm=NONE
    hi Pmenu ctermfg=103 ctermbg=231 cterm=NONE
    hi StatusLine ctermfg=103 ctermbg=231 cterm=NONE
    hi TabLine ctermfg=103 ctermbg=231 cterm=NONE
    hi TabLineFill ctermfg=NONE ctermbg=231 cterm=NONE
  endif
  if !s:italics 
    hi Comment ctermfg=103 ctermbg=NONE cterm=NONE
  else
    hi Comment ctermfg=103 ctermbg=NONE cterm=italic
    if !s:italics
      hi Comment cterm=NONE
    endif
  endif
  hi ColorColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=255 cterm=NONE
  hi CursorLineNr ctermfg=60 ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=254 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=255 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=224 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=224 cterm=NONE
  hi Directory ctermfg=66 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=132 ctermbg=NONE cterm=bold
  hi FloatBorder ctermfg=253 ctermbg=NONE cterm=NONE
  hi FloatTitle ctermfg=103 ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=103 ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=255 ctermbg=174 cterm=NONE
  hi LineNr ctermfg=103 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=60 ctermbg=253 cterm=NONE
  hi ModeMsg ctermfg=103 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=103 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=103 ctermbg=NONE cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=255 cterm=NONE
  hi PmenuSel ctermfg=60 ctermbg=255 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=253 cterm=NONE
  hi Question ctermfg=172 ctermbg=NONE cterm=NONE
  hi Search ctermfg=NONE ctermbg=253 cterm=NONE
  hi SpecialKey ctermfg=66 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi TabLineSel ctermfg=60 ctermbg=255 cterm=NONE
  hi Title ctermfg=60 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=253 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=253 cterm=NONE
  hi WarningMsg ctermfg=172 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=174 ctermbg=NONE cterm=NONE
  hi Character ctermfg=172 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=24 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=172 ctermbg=NONE cterm=NONE
  hi Debug ctermfg=174 ctermbg=NONE cterm=NONE
  hi Define ctermfg=103 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=103 ctermbg=NONE cterm=NONE
  hi Error ctermfg=132 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=24 ctermbg=NONE cterm=NONE
  hi Float ctermfg=172 ctermbg=NONE cterm=NONE
  hi Function ctermfg=174 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=174 ctermbg=NONE cterm=NONE
  hi Include ctermfg=103 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=24 ctermbg=NONE cterm=NONE
  hi Label ctermfg=66 ctermbg=NONE cterm=NONE
  hi Macro ctermfg=103 ctermbg=NONE cterm=NONE
  hi Number ctermfg=172 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=103 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=103 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=103 ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=24 ctermbg=NONE cterm=NONE
  hi Special ctermfg=174 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=174 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=103 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=24 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=66 ctermbg=NONE cterm=NONE
  hi String ctermfg=172 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=66 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=174 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=103 ctermbg=NONE cterm=NONE
  hi Type ctermfg=66 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=66 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlArg ctermfg=103 ctermbg=NONE cterm=NONE
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlEndTag ctermfg=103 ctermbg=NONE cterm=NONE
  hi htmlH1 ctermfg=103 ctermbg=NONE cterm=bold
  hi htmlH2 ctermfg=66 ctermbg=NONE cterm=bold
  hi htmlH3 ctermfg=174 ctermbg=NONE cterm=bold
  hi htmlH4 ctermfg=172 ctermbg=NONE cterm=bold
  hi htmlH5 ctermfg=24 ctermbg=NONE cterm=bold
  if !s:italics 
    hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=NONE
  else
    hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
    if !s:italics
      hi htmlItalic cterm=NONE
    endif
  endif
  hi htmlLink ctermfg=103 ctermbg=NONE cterm=NONE
  hi htmlTag ctermfg=103 ctermbg=NONE cterm=NONE
  hi htmlTagN ctermfg=60 ctermbg=NONE cterm=NONE
  hi htmlTagName ctermfg=66 ctermbg=NONE cterm=NONE
  hi markdownDelimiter ctermfg=103 ctermbg=NONE cterm=NONE
  hi markdownH1 ctermfg=103 ctermbg=NONE cterm=bold
  hi markdownH2 ctermfg=66 ctermbg=NONE cterm=bold
  hi markdownH3 ctermfg=174 ctermbg=NONE cterm=bold
  hi markdownH4 ctermfg=172 ctermbg=NONE cterm=bold
  hi markdownH5 ctermfg=24 ctermbg=NONE cterm=bold
  hi markdownH6 ctermfg=66 ctermbg=NONE cterm=bold
  hi markdownLinkText ctermfg=103 ctermbg=NONE cterm=underline
  if !s:italics 
    hi mkdCode ctermfg=66 ctermbg=NONE cterm=NONE
  else
    hi mkdCode ctermfg=66 ctermbg=NONE cterm=italic
    if !s:italics
      hi mkdCode cterm=NONE
    endif
  endif
  hi mkdCodeDelimiter ctermfg=174 ctermbg=NONE cterm=NONE
  hi mkdCodeEnd ctermfg=66 ctermbg=NONE cterm=NONE
  hi mkdCodeStart ctermfg=66 ctermbg=NONE cterm=NONE
  hi mkdFootnotes ctermfg=66 ctermbg=NONE cterm=NONE
  hi mkdID ctermfg=66 ctermbg=NONE cterm=underline
  hi mkdInlineURL ctermfg=103 ctermbg=NONE cterm=underline
  hi mkdListItemLine ctermfg=60 ctermbg=NONE cterm=NONE
  hi mkdRule ctermfg=103 ctermbg=NONE cterm=NONE
  hi VimwikiHR ctermfg=103 ctermbg=NONE cterm=NONE
  hi VimwikiHeader1 ctermfg=103 ctermbg=NONE cterm=bold
  hi VimwikiHeader2 ctermfg=66 ctermbg=NONE cterm=bold
  hi VimwikiHeader3 ctermfg=174 ctermbg=NONE cterm=bold
  hi VimwikiHeader4 ctermfg=172 ctermbg=NONE cterm=bold
  hi VimwikiHeader5 ctermfg=24 ctermbg=NONE cterm=bold
  hi VimwikiHeader6 ctermfg=66 ctermbg=NONE cterm=bold
  hi VimwikiHeaderChar ctermfg=24 ctermbg=NONE cterm=NONE
  hi VimwikiLink ctermfg=103 ctermbg=NONE cterm=underline
  hi VimwikiList ctermfg=103 ctermbg=NONE cterm=NONE
  hi VimwikiNoExistsLink ctermfg=132 ctermbg=NONE cterm=NONE
  unlet s:t_Co s:italics
  finish
endif

" Background: light
" Color: base           #faf4ed ~
" Color: surface        #fffaf3 ~
" Color: overlay        #f2e9e1 ~
" Color: muted          #9893a5 ~
" Color: subtle         #797593 ~
" Color: text           #575279 ~
" Color: love           #b4637a ~
" Color: gold           #ea9d34 ~
" Color: rose           #d7827e ~
" Color: pine           #286983 ~
" Color: foam           #56949f ~
" Color: iris           #907aa9 ~
" Color: highlight_low  #f4ede8 ~
" Color: highlight_med  #dfdad9 ~
" Color: highlight_high #cecacd ~
" Color: diff_add       #d9e1dd ~
" Color: diff_delete    #ecd7d6 ~
" Color: diff_text      #f3ddd7 ~
" Term colors: overlay love pine gold
" Term colors: foam    iris rose text
" Term colors: subtle  love pine gold
" Term colors: foam    iris rose text
" vim: et ts=2 sw=2
